version: '3.8'
services:
  back:
    build: ./api
    ports:
      - "3001:3001"
    container_name: "backapp"
    restart: always
    volumes:
      - /media/back:/usr/src/app/backend/prisma/db/
  front:
    build: ./schedule
    ports:
      - "3000:3000"
    restart: always
volumes:
  back: