FROM node:current-alpine
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/front

WORKDIR /usr/src/app/front

COPY package*.json ./
COPY .env.local ./

RUN npm config rm proxy 
RUN npm config rm https-proxy --tried removing npm proxy 

RUN npm install

COPY . .

EXPOSE 3000
RUN npm run build

CMD [ "npm", "run", "start" ]