FROM node:20-alpine3.17
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/front

WORKDIR /usr/src/app/front

COPY package*.json ./
COPY .env.local ./

RUN npm install

COPY . .

EXPOSE 3000
RUN npm run build

CMD [ "npm", "run", "start" ]