import './globals.css'
import { Poppins } from 'next/font/google'
import {GeneralProvider} from '@/lib/context/genralContext'
import {BubbleProvider} from '@/lib/context/Bubble'
import {Bubble} from './Bubble'

const inter = Poppins({
  subsets: ['latin-ext'],
  weight: ['400', '700', '800'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GeneralProvider>
        <BubbleProvider>
        <body className={inter.className}>
          <Bubble/>
          {children}
          </body>
        </BubbleProvider>
      </GeneralProvider>
    </html>
  )
}
