FROM node:current-alpine3.17
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/backend

WORKDIR /usr/src/app/backend

COPY package*.json ./
COPY prisma ./prisma
# COPY .env ./
# RUN  cat .env
RUN npm config rm proxy 
RUN npm config rm https-proxy --tried removing npm proxy 
RUN npm install 
RUN npm run migrate
RUN npm run generate
RUN npm i -D @types/express @types/cors 
RUN npm i ts-node

COPY . .

EXPOSE 3001

RUN npm run init

CMD [ "npm", "run", "dev" ]